name: Discord

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content": "Discord webhook test. Roger! Roger!"}' \
            ${{ secrets.OSS_GUILD_DISCORD_WEBHOOK }}
